### PR TITLE
Adding hint re: seed data to README

### LINKED ISSUE #1: Spec Issues
Spec does not properly initialize with a user. DB cleaner runs before specs, and seed file does not seed any user data, causing:

@user = User.first

to return nil.

### PR DESCRIPTION
**Pull request by PeterBell**
Designed to fix https://github.com/learn-co-curriculum/flatiron-store-project/issues/1#issuecomment-203459073

### CODE REVIEW

**Comment by jmburges** [comment]
:+1:

**Comment by jmburges** [comment]
actually, I think we should pull it out of the hints. I'm afraid that they won't read it and still will be frustrated.

**Comment by PeterBell** [comment]
Hey @jmburges not sure I understand your latest comment. Should we delete the hint? Move the hint elsewhere (if so, exactly where)? Add the seed data? Please clarify and I'll get it sorted!

**Comment by jmburges** [comment]
sorry! Definitely don't delete it, I was thinking maybe just put it in the "instructions" it self or something like that? Just want to make sure they see it and don't gloss over the hint

**Comment by PeterBell** [comment]
Does that look better @jmburges ?

**Comment by pletcher** [comment]
I think this is good for addressing #1. We want to get students used to having to set tests up -- they won't always have the pre-written, after all -- and this seems to give them enough info to get rolling.

:ship:

**Comment by PeterBell** [comment]
Awesome - I'll merge it in then @pletcher ! cc @jmburges and @AnnJohn

**Pull request merged**
